FROM registry.centos.org/centos/centos:7

RUN yum install -y gcc &&\
    yum install -y epel-release &&\
    yum install -y python34-pip &&\
    yum install -y python34-devel &&\
    yum clean all

RUN mkdir -p /models
WORKDIR /models

RUN pip3 install --upgrade pip
RUN pip3 install alembic psycopg2-binary

ENTRYPOINT ["bash", "-c"]
